In [ ]:
🎯 Day 4 Practice Checklist

Before moving to Day 5, make sure you can confidently answer yes to each of these:

☐ Create a DataFrame with missing values.
☐ Detect missing values using isnull() and isna().
☐ Count missing values in each column and in the whole DataFrame.
☐ Remove rows or columns with dropna().
☐ Use subset and thresh with dropna().
☐ Fill missing values with a constant, mean, median, and mode.
☐ Apply ffill() and bfill().
☐ Use interpolate() for numeric data.
☐ Replace values using replace().
☐ Detect and remove duplicate rows.
☐ Save the cleaned DataFrame to CSV and Excel.

If you master these topics, you'll have covered the core data-cleaning operations that are used in almost every real-world Pandas project.

# Data cleaning

In [7]:
#import the libraries

import pandas as pd

df = pd.read_csv("pandas_missing_values_practice_100.csv")

df

    CustomerID   Name   Age       City    Salary Department  Experience
0            1  David  43.0  Hyderabad   70586.0      Sales        13.0
1            2  Frank  35.0    Chennai       NaN      Sales        17.0
2            3    Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4    Eva  46.0    Chennai  114825.0    Finance         1.0
4            5    Ivy  50.0     Mumbai  101142.0         IT         NaN
..         ...    ...   ...        ...       ...        ...         ...
95          96  Grace  58.0      Delhi  109523.0         HR        20.0
96          97  David  60.0       Pune  108513.0        NaN        10.0
97          98    NaN  60.0       Pune       NaN         IT        16.0
98          99    Bob  21.0  Bengaluru       NaN    Finance        15.0
99         100  Alice  51.0    Chennai   53748.0         IT         5.0

[100 rows x 7 columns]

## step -1 Detecting the missing values

In [8]:
df.isnull()

    CustomerID   Name    Age   City  Salary  Department  Experience
0        False  False  False  False   False       False       False
1        False  False  False  False    True       False       False
2        False  False  False  False   False       False       False
3        False  False  False  False   False       False       False
4        False  False  False  False   False       False        True
..         ...    ...    ...    ...     ...         ...         ...
95       False  False  False  False   False       False       False
96       False  False  False  False   False        True       False
97       False   True  False  False    True       False       False
98       False  False  False  False    True       False       False
99       False  False  False  False   False       False       False

[100 rows x 7 columns]

## count the missing values in each column

In [9]:
# count the total number of missing values 


df.isnull().sum()

CustomerID     0
Name          10
Age           10
City           5
Salary        18
Department    11
Experience    11
dtype: int64

## step -2  drop the rows or column contain the null missing values

In [15]:

df.dropna()

    CustomerID     Name   Age       City    Salary Department  Experience
0            1    David  43.0  Hyderabad   70586.0      Sales        13.0
2            3      Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4      Eva  46.0    Chennai  114825.0    Finance         1.0
7            8  Charlie  46.0      Delhi   59274.0    Support         5.0
8            9    David  51.0    Chennai   50500.0         HR        10.0
9           10    Henry  25.0    Chennai   63048.0         IT        12.0
13          14    Grace  48.0       Pune   70534.0         IT         0.0
14          15      Eva  47.0      Delhi   62564.0    Support         3.0
15          16    David  45.0     Mumbai   60364.0         HR        13.0
16          17      Ivy  21.0  Hyderabad   35938.0    Support         5.0
17          18    Henry  52.0       Pune   27928.0    Support        20.0
18          19      Ivy  49.0  Bengaluru   32611.0         HR         5.0
22          23    Frank  56.0  Hyderabad   36986.0         IT        10.0
23          24    Alice  27.0       Pune   98668.0         HR         1.0
24          25      Ivy  30.0     Mumbai   38705.0         IT         4.0
27          28    David  57.0     Mumbai   87393.0    Support        14.0
29          30      Eva  46.0       Pune   44751.0      Sales        18.0
30          31  Charlie  22.0  Bengaluru   78178.0    Support        11.0
31          32      Bob  54.0    Chennai  100068.0         HR        11.0
35          36     Jack  23.0  Bengaluru  119233.0    Finance        13.0
36          37      Eva  32.0  Hyderabad   91189.0    Support         2.0
38          39    Henry  25.0      Delhi   56466.0         IT         0.0
41          42      Bob  43.0      Delhi   62632.0    Support         4.0
48          49     Jack  52.0       Pune   68514.0      Sales        17.0
50          51      Bob  26.0    Chennai   84125.0      Sales         0.0
51          52     Jack  32.0  Hyderabad  107204.0    Finance        18.0
52          53    Alice  36.0     Mumbai   30332.0    Support        17.0
54          55      Eva  38.0       Pune   28623.0         HR         2.0
56          57    Henry  52.0      Delhi   99364.0         HR         7.0
57          58    David  43.0      Delhi  108673.0      Sales         5.0
60          61    David  31.0  Bengaluru  110714.0    Support        11.0
61          62    Grace  35.0       Pune   97766.0         HR         0.0
62          63  Charlie  27.0      Delhi   77804.0         HR        16.0
63          64     Jack  53.0  Bengaluru  115823.0         HR         2.0
68          69    David  36.0  Hyderabad   72685.0    Support         5.0
70          71  Charlie  27.0    Chennai  111120.0    Support        13.0
73          74      Ivy  55.0     Mumbai   80804.0         IT        14.0
75          76      Eva  23.0  Bengaluru   77627.0    Finance         9.0
76          77  Charlie  41.0  Bengaluru   40620.0         HR         6.0
78          79      Ivy  54.0     Mumbai   28043.0    Finance        13.0
79          80    Frank  41.0  Hyderabad  110198.0    Finance        14.0
82          83    Frank  55.0       Pune   91974.0         IT        19.0
84          85      Eva  25.0       Pune   87602.0         HR         0.0
87          88    Alice  58.0  Hyderabad   69614.0         IT        19.0
94          95    Frank  24.0  Bengaluru   77559.0    Finance         6.0
95          96    Grace  58.0      Delhi  109523.0         HR        20.0
99         100    Alice  51.0    Chennai   53748.0         IT         5.0

In [18]:
df

    CustomerID   Name   Age       City    Salary Department  Experience
0            1  David  43.0  Hyderabad   70586.0      Sales        13.0
1            2  Frank  35.0    Chennai       NaN      Sales        17.0
2            3    Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4    Eva  46.0    Chennai  114825.0    Finance         1.0
4            5    Ivy  50.0     Mumbai  101142.0         IT         NaN
..         ...    ...   ...        ...       ...        ...         ...
95          96  Grace  58.0      Delhi  109523.0         HR        20.0
96          97  David  60.0       Pune  108513.0        NaN        10.0
97          98    NaN  60.0       Pune       NaN         IT        16.0
98          99    Bob  21.0  Bengaluru       NaN    Finance        15.0
99         100  Alice  51.0    Chennai   53748.0         IT         5.0

[100 rows x 7 columns]

In [16]:
df.dropna(axis =1)

    CustomerID
0            1
1            2
2            3
3            4
4            5
..         ...
95          96
96          97
97          98
98          99
99         100

[100 rows x 1 columns]

In [17]:
df

    CustomerID   Name   Age       City    Salary Department  Experience
0            1  David  43.0  Hyderabad   70586.0      Sales        13.0
1            2  Frank  35.0    Chennai       NaN      Sales        17.0
2            3    Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4    Eva  46.0    Chennai  114825.0    Finance         1.0
4            5    Ivy  50.0     Mumbai  101142.0         IT         NaN
..         ...    ...   ...        ...       ...        ...         ...
95          96  Grace  58.0      Delhi  109523.0         HR        20.0
96          97  David  60.0       Pune  108513.0        NaN        10.0
97          98    NaN  60.0       Pune       NaN         IT        16.0
98          99    Bob  21.0  Bengaluru       NaN    Finance        15.0
99         100  Alice  51.0    Chennai   53748.0         IT         5.0

[100 rows x 7 columns]

In [19]:
df.dropna(how = 'any')

    CustomerID     Name   Age       City    Salary Department  Experience
0            1    David  43.0  Hyderabad   70586.0      Sales        13.0
2            3      Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4      Eva  46.0    Chennai  114825.0    Finance         1.0
7            8  Charlie  46.0      Delhi   59274.0    Support         5.0
8            9    David  51.0    Chennai   50500.0         HR        10.0
9           10    Henry  25.0    Chennai   63048.0         IT        12.0
13          14    Grace  48.0       Pune   70534.0         IT         0.0
14          15      Eva  47.0      Delhi   62564.0    Support         3.0
15          16    David  45.0     Mumbai   60364.0         HR        13.0
16          17      Ivy  21.0  Hyderabad   35938.0    Support         5.0
17          18    Henry  52.0       Pune   27928.0    Support        20.0
18          19      Ivy  49.0  Bengaluru   32611.0         HR         5.0
22          23    Frank  56.0  Hyderabad   36986.0         IT        10.0
23          24    Alice  27.0       Pune   98668.0         HR         1.0
24          25      Ivy  30.0     Mumbai   38705.0         IT         4.0
27          28    David  57.0     Mumbai   87393.0    Support        14.0
29          30      Eva  46.0       Pune   44751.0      Sales        18.0
30          31  Charlie  22.0  Bengaluru   78178.0    Support        11.0
31          32      Bob  54.0    Chennai  100068.0         HR        11.0
35          36     Jack  23.0  Bengaluru  119233.0    Finance        13.0
36          37      Eva  32.0  Hyderabad   91189.0    Support         2.0
38          39    Henry  25.0      Delhi   56466.0         IT         0.0
41          42      Bob  43.0      Delhi   62632.0    Support         4.0
48          49     Jack  52.0       Pune   68514.0      Sales        17.0
50          51      Bob  26.0    Chennai   84125.0      Sales         0.0
51          52     Jack  32.0  Hyderabad  107204.0    Finance        18.0
52          53    Alice  36.0     Mumbai   30332.0    Support        17.0
54          55      Eva  38.0       Pune   28623.0         HR         2.0
56          57    Henry  52.0      Delhi   99364.0         HR         7.0
57          58    David  43.0      Delhi  108673.0      Sales         5.0
60          61    David  31.0  Bengaluru  110714.0    Support        11.0
61          62    Grace  35.0       Pune   97766.0         HR         0.0
62          63  Charlie  27.0      Delhi   77804.0         HR        16.0
63          64     Jack  53.0  Bengaluru  115823.0         HR         2.0
68          69    David  36.0  Hyderabad   72685.0    Support         5.0
70          71  Charlie  27.0    Chennai  111120.0    Support        13.0
73          74      Ivy  55.0     Mumbai   80804.0         IT        14.0
75          76      Eva  23.0  Bengaluru   77627.0    Finance         9.0
76          77  Charlie  41.0  Bengaluru   40620.0         HR         6.0
78          79      Ivy  54.0     Mumbai   28043.0    Finance        13.0
79          80    Frank  41.0  Hyderabad  110198.0    Finance        14.0
82          83    Frank  55.0       Pune   91974.0         IT        19.0
84          85      Eva  25.0       Pune   87602.0         HR         0.0
87          88    Alice  58.0  Hyderabad   69614.0         IT        19.0
94          95    Frank  24.0  Bengaluru   77559.0    Finance         6.0
95          96    Grace  58.0      Delhi  109523.0         HR        20.0
99         100    Alice  51.0    Chennai   53748.0         IT         5.0

In [25]:
df.dropna(how = 'all')

    CustomerID     Name   Age       City    Salary Department  Experience
0            1    David  43.0  Hyderabad   70586.0      Sales        13.0
2            3      Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4      Eva  46.0    Chennai  114825.0    Finance         1.0
7            8  Charlie  46.0      Delhi   59274.0    Support         5.0
8            9    David  51.0    Chennai   50500.0         HR        10.0
9           10    Henry  25.0    Chennai   63048.0         IT        12.0
13          14    Grace  48.0       Pune   70534.0         IT         0.0
14          15      Eva  47.0      Delhi   62564.0    Support         3.0
15          16    David  45.0     Mumbai   60364.0         HR        13.0
16          17      Ivy  21.0  Hyderabad   35938.0    Support         5.0
17          18    Henry  52.0       Pune   27928.0    Support        20.0
18          19      Ivy  49.0  Bengaluru   32611.0         HR         5.0
22          23    Frank  56.0  Hyderabad   36986.0         IT        10.0
23          24    Alice  27.0       Pune   98668.0         HR         1.0
24          25      Ivy  30.0     Mumbai   38705.0         IT         4.0
27          28    David  57.0     Mumbai   87393.0    Support        14.0
29          30      Eva  46.0       Pune   44751.0      Sales        18.0
30          31  Charlie  22.0  Bengaluru   78178.0    Support        11.0
31          32      Bob  54.0    Chennai  100068.0         HR        11.0
35          36     Jack  23.0  Bengaluru  119233.0    Finance        13.0
36          37      Eva  32.0  Hyderabad   91189.0    Support         2.0
38          39    Henry  25.0      Delhi   56466.0         IT         0.0
41          42      Bob  43.0      Delhi   62632.0    Support         4.0
48          49     Jack  52.0       Pune   68514.0      Sales        17.0
50          51      Bob  26.0    Chennai   84125.0      Sales         0.0
51          52     Jack  32.0  Hyderabad  107204.0    Finance        18.0
52          53    Alice  36.0     Mumbai   30332.0    Support        17.0
54          55      Eva  38.0       Pune   28623.0         HR         2.0
56          57    Henry  52.0      Delhi   99364.0         HR         7.0
57          58    David  43.0      Delhi  108673.0      Sales         5.0
60          61    David  31.0  Bengaluru  110714.0    Support        11.0
61          62    Grace  35.0       Pune   97766.0         HR         0.0
62          63  Charlie  27.0      Delhi   77804.0         HR        16.0
63          64     Jack  53.0  Bengaluru  115823.0         HR         2.0
68          69    David  36.0  Hyderabad   72685.0    Support         5.0
70          71  Charlie  27.0    Chennai  111120.0    Support        13.0
73          74      Ivy  55.0     Mumbai   80804.0         IT        14.0
75          76      Eva  23.0  Bengaluru   77627.0    Finance         9.0
76          77  Charlie  41.0  Bengaluru   40620.0         HR         6.0
78          79      Ivy  54.0     Mumbai   28043.0    Finance        13.0
79          80    Frank  41.0  Hyderabad  110198.0    Finance        14.0
82          83    Frank  55.0       Pune   91974.0         IT        19.0
84          85      Eva  25.0       Pune   87602.0         HR         0.0
87          88    Alice  58.0  Hyderabad   69614.0         IT        19.0
94          95    Frank  24.0  Bengaluru   77559.0    Finance         6.0
95          96    Grace  58.0      Delhi  109523.0         HR        20.0
99         100    Alice  51.0    Chennai   53748.0         IT         5.0

In [28]:
df.notnull().sum()

CustomerID    47
Name          47
Age           47
City          47
Salary        47
Department    47
Experience    47
dtype: int64

In [27]:
df

    CustomerID     Name   Age       City    Salary Department  Experience
0            1    David  43.0  Hyderabad   70586.0      Sales        13.0
2            3      Ivy  59.0  Bengaluru   25377.0      Sales        16.0
3            4      Eva  46.0    Chennai  114825.0    Finance         1.0
7            8  Charlie  46.0      Delhi   59274.0    Support         5.0
8            9    David  51.0    Chennai   50500.0         HR        10.0
9           10    Henry  25.0    Chennai   63048.0         IT        12.0
13          14    Grace  48.0       Pune   70534.0         IT         0.0
14          15      Eva  47.0      Delhi   62564.0    Support         3.0
15          16    David  45.0     Mumbai   60364.0         HR        13.0
16          17      Ivy  21.0  Hyderabad   35938.0    Support         5.0
17          18    Henry  52.0       Pune   27928.0    Support        20.0
18          19      Ivy  49.0  Bengaluru   32611.0         HR         5.0
22          23    Frank  56.0  Hyderabad   36986.0         IT        10.0
23          24    Alice  27.0       Pune   98668.0         HR         1.0
24          25      Ivy  30.0     Mumbai   38705.0         IT         4.0
27          28    David  57.0     Mumbai   87393.0    Support        14.0
29          30      Eva  46.0       Pune   44751.0      Sales        18.0
30          31  Charlie  22.0  Bengaluru   78178.0    Support        11.0
31          32      Bob  54.0    Chennai  100068.0         HR        11.0
35          36     Jack  23.0  Bengaluru  119233.0    Finance        13.0
36          37      Eva  32.0  Hyderabad   91189.0    Support         2.0
38          39    Henry  25.0      Delhi   56466.0         IT         0.0
41          42      Bob  43.0      Delhi   62632.0    Support         4.0
48          49     Jack  52.0       Pune   68514.0      Sales        17.0
50          51      Bob  26.0    Chennai   84125.0      Sales         0.0
51          52     Jack  32.0  Hyderabad  107204.0    Finance        18.0
52          53    Alice  36.0     Mumbai   30332.0    Support        17.0
54          55      Eva  38.0       Pune   28623.0         HR         2.0
56          57    Henry  52.0      Delhi   99364.0         HR         7.0
57          58    David  43.0      Delhi  108673.0      Sales         5.0
60          61    David  31.0  Bengaluru  110714.0    Support        11.0
61          62    Grace  35.0       Pune   97766.0         HR         0.0
62          63  Charlie  27.0      Delhi   77804.0         HR        16.0
63          64     Jack  53.0  Bengaluru  115823.0         HR         2.0
68          69    David  36.0  Hyderabad   72685.0    Support         5.0
70          71  Charlie  27.0    Chennai  111120.0    Support        13.0
73          74      Ivy  55.0     Mumbai   80804.0         IT        14.0
75          76      Eva  23.0  Bengaluru   77627.0    Finance         9.0
76          77  Charlie  41.0  Bengaluru   40620.0         HR         6.0
78          79      Ivy  54.0     Mumbai   28043.0    Finance        13.0
79          80    Frank  41.0  Hyderabad  110198.0    Finance        14.0
82          83    Frank  55.0       Pune   91974.0         IT        19.0
84          85      Eva  25.0       Pune   87602.0         HR         0.0
87          88    Alice  58.0  Hyderabad   69614.0         IT        19.0
94          95    Frank  24.0  Bengaluru   77559.0    Finance         6.0
95          96    Grace  58.0      Delhi  109523.0         HR        20.0
99         100    Alice  51.0    Chennai   53748.0         IT         5.0