# Selecting, Indexing, and Filtering Data

## DataFrame

In [1]:
# Dataframe is a one of main data Structure in the pandaas ,
# it a table with row and columns where the data is organized

## 1 . Creating a DataFrame

In [3]:
import pandas as pd

data = {

    "Name" : ["Alice","Bob","Charlie","David"],
    "Age" : [22,25,21,24],
    "city" : ["Delhi","Mumbai","chennai","Hyderabad"],
    "marks" : [90,75,85,95]
}

print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [22, 25, 21, 24], 'city': ['Delhi', 'Mumbai', 'chennai', 'Hyderabad'], 'marks': [90, 75, 85, 95]}

In [5]:
# see the difference before and after converstion

In [4]:
# converting the ddta in to the dataframe

df = pd.DataFrame(data)

print(df)

      Name  Age       city  marks
0    Alice   22      Delhi     90
1      Bob   25     Mumbai     75
2  Charlie   21    chennai     85
3    David   24  Hyderabad     95

## 2 . Loading the dataset

In [3]:
# import libraries

import pandas as pd

data = pd.read_csv("std.csv")

data

   ID    Name  Age  Gender Department  Marks           City
0   1    Ravi   20    Male        CSE     91      Hyderabad
1   2   Priya   19  Female       AIML     88     Vijayawada
2   3    Amit   21    Male        ECE     75      Hyderabad
3   4   Sneha   20  Female        CSE     95        Chennai
4   5   Arjun   22    Male       AIML     67      Bangalore
5   6   Divya   21  Female        CSE     82      Hyderabad
6   7   Kiran   20    Male        ECE     78  Visakhapatnam
7   8  Anjali   19  Female       AIML     93      Hyderabad
8   9   Rahul   22    Male        CSE     85      Bangalore
9  10   Pooja   20  Female        ECE     89        Chennai

## Selecting a single column

In [8]:
# listing the columns

data.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'Marks', 'City'], dtype='str')

In [9]:
# Example one 

data["ID"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: ID, dtype: int64

In [10]:
#Example 2

data["Name"]

0      Ravi
1     Priya
2      Amit
3     Sneha
4     Arjun
5     Divya
6     Kiran
7    Anjali
8     Rahul
9     Pooja
Name: Name, dtype: str

In [11]:
#Example 3

data["Department"]

0     CSE
1    AIML
2     ECE
3     CSE
4    AIML
5     CSE
6     ECE
7    AIML
8     CSE
9     ECE
Name: Department, dtype: str

## 3 . selecting multiple columns

In [12]:
# Example 1

data[["ID","Name","Age"]]

# Remember one thing , when we are accessing multiple values use double brackets [[]]

   ID    Name  Age
0   1    Ravi   20
1   2   Priya   19
2   3    Amit   21
3   4   Sneha   20
4   5   Arjun   22
5   6   Divya   21
6   7   Kiran   20
7   8  Anjali   19
8   9   Rahul   22
9  10   Pooja   20

In [15]:
# Example 2

type(data[['Name','Age','Department','Gender']])

pandas.DataFrame

In [14]:
# Example 3

data[['ID','Name','Age','Marks','Gender']]


# this returns a dataframe

   ID    Name  Age  Marks  Gender
0   1    Ravi   20     91    Male
1   2   Priya   19     88  Female
2   3    Amit   21     75    Male
3   4   Sneha   20     95  Female
4   5   Arjun   22     67    Male
5   6   Divya   21     82  Female
6   7   Kiran   20     78    Male
7   8  Anjali   19     93  Female
8   9   Rahul   22     85    Male
9  10   Pooja   20     89  Female

In [ ]:

# Note : DataFrame two brackets [[]]

# Series : single bracket []

## 4 . using .loc()

In [15]:
# .loc() selects row using labels (index values)

df.loc[0]

Name     Alice
Age         22
city     Delhi
marks       90
Name: 0, dtype: object

In [23]:
# Example 2 
data.loc[4]

ID                    5
Name              Arjun
Age                  22
Gender             Male
Department         AIML
Marks                67
City          Bangalore
Name: 4, dtype: object

In [24]:
#Example 3

data.loc[:,['Gender','Age','Name']]

   Gender  Age    Name
0    Male   20    Ravi
1  Female   19   Priya
2    Male   21    Amit
3  Female   20   Sneha
4    Male   22   Arjun
5  Female   21   Divya
6    Male   20   Kiran
7  Female   19  Anjali
8    Male   22   Rahul
9  Female   20   Pooja

In [25]:
# Example - 4

data.loc[:8,:]

   ID    Name  Age  Gender Department  Marks           City
0   1    Ravi   20    Male        CSE     91      Hyderabad
1   2   Priya   19  Female       AIML     88     Vijayawada
2   3    Amit   21    Male        ECE     75      Hyderabad
3   4   Sneha   20  Female        CSE     95        Chennai
4   5   Arjun   22    Male       AIML     67      Bangalore
5   6   Divya   21  Female        CSE     82      Hyderabad
6   7   Kiran   20    Male        ECE     78  Visakhapatnam
7   8  Anjali   19  Female       AIML     93      Hyderabad
8   9   Rahul   22    Male        CSE     85      Bangalore

In [26]:
# Example 5

data.loc[0:8:2,["Name","Age",'Gender']]

    Name  Age Gender
0   Ravi   20   Male
2   Amit   21   Male
4  Arjun   22   Male
6  Kiran   20   Male
8  Rahul   22   Male

In [27]:
# Example 5

data.loc[:,:]

   ID    Name  Age  Gender Department  Marks           City
0   1    Ravi   20    Male        CSE     91      Hyderabad
1   2   Priya   19  Female       AIML     88     Vijayawada
2   3    Amit   21    Male        ECE     75      Hyderabad
3   4   Sneha   20  Female        CSE     95        Chennai
4   5   Arjun   22    Male       AIML     67      Bangalore
5   6   Divya   21  Female        CSE     82      Hyderabad
6   7   Kiran   20    Male        ECE     78  Visakhapatnam
7   8  Anjali   19  Female       AIML     93      Hyderabad
8   9   Rahul   22    Male        CSE     85      Bangalore
9  10   Pooja   20  Female        ECE     89        Chennai

In [32]:
# Example 6

data.loc[:,["Name",'Age',"Gender",'ID']]

     Name  Age  Gender  ID
0    Ravi   20    Male   1
1   Priya   19  Female   2
2    Amit   21    Male   3
3   Sneha   20  Female   4
4   Arjun   22    Male   5
5   Divya   21  Female   6
6   Kiran   20    Male   7
7  Anjali   19  Female   8
8   Rahul   22    Male   9
9   Pooja   20  Female  10

## 5 . Understanding iloc()

In [34]:
# the iloc is basesd on the positon 

# let see some example on this iloc function

In [38]:
#Example 1

data.iloc[:,:]

   ID    Name  Age  Gender Department  Marks           City
0   1    Ravi   20    Male        CSE     91      Hyderabad
1   2   Priya   19  Female       AIML     88     Vijayawada
2   3    Amit   21    Male        ECE     75      Hyderabad
3   4   Sneha   20  Female        CSE     95        Chennai
4   5   Arjun   22    Male       AIML     67      Bangalore
5   6   Divya   21  Female        CSE     82      Hyderabad
6   7   Kiran   20    Male        ECE     78  Visakhapatnam
7   8  Anjali   19  Female       AIML     93      Hyderabad
8   9   Rahul   22    Male        CSE     85      Bangalore
9  10   Pooja   20  Female        ECE     89        Chennai

In [37]:
#Example 2

data.iloc[:,:4]

   ID    Name  Age  Gender
0   1    Ravi   20    Male
1   2   Priya   19  Female
2   3    Amit   21    Male
3   4   Sneha   20  Female
4   5   Arjun   22    Male
5   6   Divya   21  Female
6   7   Kiran   20    Male
7   8  Anjali   19  Female
8   9   Rahul   22    Male
9  10   Pooja   20  Female

In [39]:
#Example 3

data.iloc[0:10:2 , 0:4]

   ID   Name  Age Gender
0   1   Ravi   20   Male
2   3   Amit   21   Male
4   5  Arjun   22   Male
6   7  Kiran   20   Male
8   9  Rahul   22   Male

In [42]:
#Example 4

data.iloc[2,:]

ID                    3
Name               Amit
Age                  21
Gender             Male
Department          ECE
Marks                75
City          Hyderabad
Name: 2, dtype: object

In [43]:
#Example 6
data.iloc[2,1]

'Amit'

In [44]:
# Example 7

data.iloc[:3,:4]

   ID   Name  Age  Gender
0   1   Ravi   20    Male
1   2  Priya   19  Female
2   3   Amit   21    Male

## 6 . Boolean indexing

## single conditon

In [45]:
# this retrives the columns based on the certain condition is satisfied

data['Marks']>90

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
Name: Marks, dtype: bool

In [46]:
#Example 2

data[data['Marks']>90]

   ID    Name  Age  Gender Department  Marks       City
0   1    Ravi   20    Male        CSE     91  Hyderabad
3   4   Sneha   20  Female        CSE     95    Chennai
7   8  Anjali   19  Female       AIML     93  Hyderabad

In [48]:
# Example 3

data[data['Department'] == 'CSE']

   ID   Name  Age  Gender Department  Marks       City
0   1   Ravi   20    Male        CSE     91  Hyderabad
3   4  Sneha   20  Female        CSE     95    Chennai
5   6  Divya   21  Female        CSE     82  Hyderabad
8   9  Rahul   22    Male        CSE     85  Bangalore

In [50]:
# Example 4 display the students whose gender is femal

data[data['Gender'] == 'Female']

   ID    Name  Age  Gender Department  Marks        City
1   2   Priya   19  Female       AIML     88  Vijayawada
3   4   Sneha   20  Female        CSE     95     Chennai
5   6   Divya   21  Female        CSE     82   Hyderabad
7   8  Anjali   19  Female       AIML     93   Hyderabad
9  10   Pooja   20  Female        ECE     89     Chennai

## multiple conditons

In [53]:
# single condition

# selecting people from city hyderabad

In [52]:
data[data['City'] == 'Hyderabad']

   ID    Name  Age  Gender Department  Marks       City
0   1    Ravi   20    Male        CSE     91  Hyderabad
2   3    Amit   21    Male        ECE     75  Hyderabad
5   6   Divya   21  Female        CSE     82  Hyderabad
7   8  Anjali   19  Female       AIML     93  Hyderabad

In [54]:
# selecting male gender people

data[data['Gender'] == 'Male']

   ID   Name  Age Gender Department  Marks           City
0   1   Ravi   20   Male        CSE     91      Hyderabad
2   3   Amit   21   Male        ECE     75      Hyderabad
4   5  Arjun   22   Male       AIML     67      Bangalore
6   7  Kiran   20   Male        ECE     78  Visakhapatnam
8   9  Rahul   22   Male        CSE     85      Bangalore

In [55]:
# both people from city hyderabab and male gender

data[(data['City'] == 'Hyderabad') & (data['Gender'] == 'Male')]

   ID  Name  Age Gender Department  Marks       City
0   1  Ravi   20   Male        CSE     91  Hyderabad
2   3  Amit   21   Male        ECE     75  Hyderabad

In [56]:
# Example 2

In [59]:
# retrive the female people and age greater > 18

data[(data['Gender'] == 'Female') & (data['Age'] > 18)]

   ID    Name  Age  Gender Department  Marks        City
1   2   Priya   19  Female       AIML     88  Vijayawada
3   4   Sneha   20  Female        CSE     95     Chennai
5   6   Divya   21  Female        CSE     82   Hyderabad
7   8  Anjali   19  Female       AIML     93   Hyderabad
9  10   Pooja   20  Female        ECE     89     Chennai

In [60]:
# or condition

In [62]:
data[(data['Gender'] == 'Female') | (data['Age'] > 18)]

   ID    Name  Age  Gender Department  Marks           City
0   1    Ravi   20    Male        CSE     91      Hyderabad
1   2   Priya   19  Female       AIML     88     Vijayawada
2   3    Amit   21    Male        ECE     75      Hyderabad
3   4   Sneha   20  Female        CSE     95        Chennai
4   5   Arjun   22    Male       AIML     67      Bangalore
5   6   Divya   21  Female        CSE     82      Hyderabad
6   7   Kiran   20    Male        ECE     78  Visakhapatnam
7   8  Anjali   19  Female       AIML     93      Hyderabad
8   9   Rahul   22    Male        CSE     85      Bangalore
9  10   Pooja   20  Female        ECE     89        Chennai

In [64]:
# using not conditon ~

data[~(data['Department'] == 'CSE')]

   ID    Name  Age  Gender Department  Marks           City
1   2   Priya   19  Female       AIML     88     Vijayawada
2   3    Amit   21    Male        ECE     75      Hyderabad
4   5   Arjun   22    Male       AIML     67      Bangalore
6   7   Kiran   20    Male        ECE     78  Visakhapatnam
7   8  Anjali   19  Female       AIML     93      Hyderabad
9  10   Pooja   20  Female        ECE     89        Chennai

## 7 . using isin