# Grouping, Aggregation & Sorting

## 🎯 Day 6 Goal

In [ ]:

By the end of this session, you will learn how to:

Sort data
Group data
Perform aggregation
Use multiple aggregation functions
Filter groups
Transform grouped data
Rank data within groups
Find top records
Count unique values

In [1]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.296 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [4]:
#loading the dataset

import pandas as pd

data = pd.read_csv("dataset-6.csv")

data

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9
6,107,Anjali,HR,Female,Mumbai,50000,3500,5,4.4
7,108,Aman,Sales,Male,Delhi,47000,2800,3,4.0
8,109,Ritika,Finance,Female,Hyderabad,60000,4500,6,4.6
9,110,Deepak,IT,Male,Chennai,76000,8000,6,4.7
10,111,Neha,Marketing,Female,Delhi,52000,3200,4,4.2
11,112,Rohit,Marketing,Male,Mumbai,55000,3500,5,4.3
12,113,Priya,Sales,Female,Hyderabad,49000,2700,2,4.0
13,114,Ajay,Finance,Male,Bangalore,61000,5000,7,4.5
14,115,Meera,IT,Female,Delhi,69000,6000,4,4.6
15,116,Suresh,HR,Male,Hyderabad,53000,3800,6,4.3
16,117,Kavya,Marketing,Female,Bangalore,58000,4000,5,4.5
17,118,Varun,Sales,Male,Mumbai,51000,3100,4,4.1
18,119,Divya,Finance,Female,Chennai,64000,5200,8,4.8
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9

In [5]:
data.head()

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9

In [6]:
data.tail()

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
15,116,Suresh,HR,Male,Hyderabad,53000,3800,6,4.3
16,117,Kavya,Marketing,Female,Bangalore,58000,4000,5,4.5
17,118,Varun,Sales,Male,Mumbai,51000,3100,4,4.1
18,119,Divya,Finance,Female,Chennai,64000,5200,8,4.8
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9

In [8]:
data = pd.DataFrame(data)

# part 1 sorting

In [10]:
data.columns

Index(['EmployeeID', 'Name', 'Department', 'Gender', 'City', 'Salary', 'Bonus',
       'Experience', 'Rating'],
      dtype='str')

## Ascending order

In [12]:
data.sort_values('Salary',ascending = True)

# ascending means small to big , 

# from out example , it display the salary with low to high 

# by default it is in ascending order

data.sort_values("Salary")

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9
7,108,Aman,Sales,Male,Delhi,47000,2800,3,4.0
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2
12,113,Priya,Sales,Female,Hyderabad,49000,2700,2,4.0
6,107,Anjali,HR,Female,Mumbai,50000,3500,5,4.4
17,118,Varun,Sales,Male,Mumbai,51000,3100,4,4.1
10,111,Neha,Marketing,Female,Delhi,52000,3200,4,4.2
15,116,Suresh,HR,Male,Hyderabad,53000,3800,6,4.3
11,112,Rohit,Marketing,Male,Mumbai,55000,3500,5,4.3
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1
16,117,Kavya,Marketing,Female,Bangalore,58000,4000,5,4.5
8,109,Ritika,Finance,Female,Hyderabad,60000,4500,6,4.6
13,114,Ajay,Finance,Male,Bangalore,61000,5000,7,4.5
18,119,Divya,Finance,Female,Chennai,64000,5200,8,4.8
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5
14,115,Meera,IT,Female,Delhi,69000,6000,4,4.6
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8
9,110,Deepak,IT,Male,Chennai,76000,8000,6,4.7
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9

## Descending order

In [13]:
data.sort_values('Salary',ascending = False)

# From this i understand that the max salary among all the employeess is 82000

# Decending means big to small

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9
9,110,Deepak,IT,Male,Chennai,76000,8000,6,4.7
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8
14,115,Meera,IT,Female,Delhi,69000,6000,4,4.6
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5
18,119,Divya,Finance,Female,Chennai,64000,5200,8,4.8
13,114,Ajay,Finance,Male,Bangalore,61000,5000,7,4.5
8,109,Ritika,Finance,Female,Hyderabad,60000,4500,6,4.6
16,117,Kavya,Marketing,Female,Bangalore,58000,4000,5,4.5
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1
11,112,Rohit,Marketing,Male,Mumbai,55000,3500,5,4.3
15,116,Suresh,HR,Male,Hyderabad,53000,3800,6,4.3
10,111,Neha,Marketing,Female,Delhi,52000,3200,4,4.2
17,118,Varun,Sales,Male,Mumbai,51000,3100,4,4.1
6,107,Anjali,HR,Female,Mumbai,50000,3500,5,4.4
12,113,Priya,Sales,Female,Hyderabad,49000,2700,2,4.0
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2
7,108,Aman,Sales,Male,Delhi,47000,2800,3,4.0
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9

## Multiple columns

In [17]:
# task is sort the department by alpahbetical order 
# sort the employees based on their salary in decending order

data.sort_values(
    by =['Department','Salary'],
    ascending = [True,False]
)

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
18,119,Divya,Finance,Female,Chennai,64000,5200,8,4.8
13,114,Ajay,Finance,Male,Bangalore,61000,5000,7,4.5
8,109,Ritika,Finance,Female,Hyderabad,60000,4500,6,4.6
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1
15,116,Suresh,HR,Male,Hyderabad,53000,3800,6,4.3
6,107,Anjali,HR,Female,Mumbai,50000,3500,5,4.4
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9
9,110,Deepak,IT,Male,Chennai,76000,8000,6,4.7
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8
14,115,Meera,IT,Female,Delhi,69000,6000,4,4.6
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5
16,117,Kavya,Marketing,Female,Bangalore,58000,4000,5,4.5
11,112,Rohit,Marketing,Male,Mumbai,55000,3500,5,4.3
10,111,Neha,Marketing,Female,Delhi,52000,3200,4,4.2
17,118,Varun,Sales,Male,Mumbai,51000,3100,4,4.1
12,113,Priya,Sales,Female,Hyderabad,49000,2700,2,4.0
7,108,Aman,Sales,Male,Delhi,47000,2800,3,4.0
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9

## sort_index()

In [18]:
data.sort_index()

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9
6,107,Anjali,HR,Female,Mumbai,50000,3500,5,4.4
7,108,Aman,Sales,Male,Delhi,47000,2800,3,4.0
8,109,Ritika,Finance,Female,Hyderabad,60000,4500,6,4.6
9,110,Deepak,IT,Male,Chennai,76000,8000,6,4.7
10,111,Neha,Marketing,Female,Delhi,52000,3200,4,4.2
11,112,Rohit,Marketing,Male,Mumbai,55000,3500,5,4.3
12,113,Priya,Sales,Female,Hyderabad,49000,2700,2,4.0
13,114,Ajay,Finance,Male,Bangalore,61000,5000,7,4.5
14,115,Meera,IT,Female,Delhi,69000,6000,4,4.6
15,116,Suresh,HR,Male,Hyderabad,53000,3800,6,4.3
16,117,Kavya,Marketing,Female,Bangalore,58000,4000,5,4.5
17,118,Varun,Sales,Male,Mumbai,51000,3100,4,4.1
18,119,Divya,Finance,Female,Chennai,64000,5200,8,4.8
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9

# Part 2

## Group by

In [ ]:
Instead of manually filtering each department, groupby() does it automatically.

In [ ]:
# Finding the average salary of each department

In [19]:
data.groupby('Department')['Salary'].mean()

Department
Finance      60250.000000
HR           50333.333333
IT           73833.333333
Marketing    55000.000000
Sales        48000.000000
Name: Salary, dtype: float64

## max salary from each department

In [20]:
data.groupby('Department')['Salary'].max()

Department
Finance      64000
HR           53000
IT           82000
Marketing    58000
Sales        51000
Name: Salary, dtype: int64

## min salary from each department

In [21]:
data.groupby('Department')['Salary'].min()

Department
Finance      56000
HR           48000
IT           65000
Marketing    52000
Sales        45000
Name: Salary, dtype: int64

## count employee from each department

In [23]:
data.groupby('Department')['EmployeeID'].count()

Department
Finance      4
HR           3
IT           6
Marketing    3
Sales        4
Name: EmployeeID, dtype: int64

## Group by multiple columns

In [24]:
data.groupby(
    ['Department','Gender']
)['Salary'].mean()

Department  Gender
Finance     Female    60000.000000
            Male      61000.000000
HR          Female    49000.000000
            Male      53000.000000
IT          Female    69000.000000
            Male      74800.000000
Marketing   Female    55000.000000
            Male      55000.000000
Sales       Female    49000.000000
            Male      47666.666667
Name: Salary, dtype: float64

In [25]:
# Example - 1 , display the employee name from each department whose getting max salary 

data.groupby(
    ['Department','Name']
)['Salary'].max()

Department  Name
Finance     Ajay      61000
            Divya     64000
            Pooja     56000
            Ritika    60000
HR          Anjali    50000
            Sneha     48000
            Suresh    53000
IT          Arjun     72000
            Deepak    76000
            Kiran     82000
            Meera     69000
            Nikhil    79000
            Rahul     65000
Marketing   Kavya     58000
            Neha      52000
            Rohit     55000
Sales       Aman      47000
            Priya     49000
            Varun     51000
            Vijay     45000
Name: Salary, dtype: int64

## Part 4 Aggregrate functions

In [26]:
# sum of all employee salaries

data['Salary'].sum()

np.int64(1192000)

In [27]:
# Max salary from all employee salaries

data['Salary'].max()

np.int64(82000)

In [29]:
# Min salary from all employee salaries

data['Salary'].min()

np.int64(45000)

In [30]:
# average salary form all employee salaries

data['Salary'].mean()

np.float64(59600.0)

In [31]:
# standard deviation

data['Salary'].std()

np.float64(11151.587094976307)

In [32]:
# variance

data['Salary'].var()

np.float64(124357894.73684211)

# part 4 agg()

In [33]:
# instead of calculating one by one ,we can calculate all together

data.groupby('Department')['Salary'].agg(
    ['mean','max','min','std','var']
)

                    mean    max    min          std           var
Department
Finance     60250.000000  64000  56000  3304.037934  1.091667e+07
HR          50333.333333  53000  48000  2516.611478  6.333333e+06
IT          73833.333333  82000  65000  6369.196705  4.056667e+07
Marketing   55000.000000  58000  52000  3000.000000  9.000000e+06
Sales       48000.000000  51000  45000  2581.988897  6.666667e+06

In [35]:
# multiple columns

data.groupby('Department').agg(
    {
        'Salary' : ['mean','max','min','count'],
        'Bonus' : 'sum',
        'Rating' : 'mean'
    }
)

                  Salary                      Bonus    Rating
                    mean    max    min count    sum      mean
Department
Finance     60250.000000  64000  56000     4  18700  4.500000
HR          50333.333333  53000  48000     3  10300  4.300000
IT          73833.333333  82000  65000     6  43500  4.733333
Marketing   55000.000000  58000  52000     3  10700  4.333333
Sales       48000.000000  51000  45000     4  11100  4.000000

# part 6 transform

In [ ]:
Unlike aggregation, which returns one value per group, transformation returns one value for every row.

Example:

Every employee receives the average salary of their own department as a new column.

In [37]:
data['Dept_avg'] = data.groupby('Department')['Salary'].transform('mean') 


data['Dept_avg']

0     73833.333333
1     50333.333333
2     73833.333333
3     60250.000000
4     48000.000000
5     73833.333333
6     50333.333333
7     48000.000000
8     60250.000000
9     73833.333333
10    55000.000000
11    55000.000000
12    48000.000000
13    60250.000000
14    73833.333333
15    50333.333333
16    55000.000000
17    48000.000000
18    60250.000000
19    73833.333333
Name: Dept_avg, dtype: float64

In [38]:
data.head()

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating,Dept_avg
0,101,Rahul,IT,Male,Hyderabad,65000,5000,2,4.5,73833.333333
1,102,Sneha,HR,Female,Mumbai,48000,3000,3,4.2,50333.333333
2,103,Arjun,IT,Male,Hyderabad,72000,7000,5,4.8,73833.333333
3,104,Pooja,Finance,Female,Delhi,56000,4000,4,4.1,60250.000000
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9,48000.000000

In [40]:
data.loc[0:5,['Department','Dept_avg']]

  Department      Dept_avg
0         IT  73833.333333
1         HR  50333.333333
2         IT  73833.333333
3    Finance  60250.000000
4      Sales  48000.000000
5         IT  73833.333333

# part 7 rank()

In [ ]:
Ranking helps identify the highest and lowest values within each group.

Examples:

Highest-paid employee in every department
Top performer in every city
Rank employees based on experience

Function
rank()
8. Top Records

In [45]:
# Rank employees by salary within each department.

data['Rank'] = data.groupby('Department')['Salary'].rank(ascending =False)


data['Rank']

0     6.0
1     3.0
2     4.0
3     4.0
4     4.0
5     1.0
6     2.0
7     3.0
8     3.0
9     3.0
10    3.0
11    2.0
12    2.0
13    2.0
14    5.0
15    1.0
16    1.0
17    1.0
18    1.0
19    2.0
Name: Rank, dtype: float64

# Part 8 Top Records

In [ ]:
8. Top Records

Sometimes we need only the highest or lowest values.

Examples:

Top 5 salaries
Top employee from each department
Top-rated employees
Functions
nlargest()
nsmallest()

In [47]:
# highest salary

data.nlargest(1,'Salary')

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating,Dept_avg,Rank
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9,73833.333333,1.0

In [48]:
# second latgest salary

data.nlargest(2,'Salary')

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating,Dept_avg,Rank
5,106,Kiran,IT,Male,Bangalore,82000,9000,7,4.9,73833.333333,1.0
19,120,Nikhil,IT,Male,Delhi,79000,8500,8,4.9,73833.333333,2.0

In [50]:
# lowest slary 

data.nsmallest(1,'Salary')

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating,Dept_avg,Rank
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9,48000.0,4.0

In [52]:
# second lowest salary 

data.nsmallest(2,'Salary')

,EmployeeID,Name,Department,Gender,City,Salary,Bonus,Experience,Rating,Dept_avg,Rank
4,105,Vijay,Sales,Male,Chennai,45000,2500,2,3.9,48000.0,4.0
7,108,Aman,Sales,Male,Delhi,47000,2800,3,4.0,48000.0,3.0

In [54]:
# Top salary from each department

data.groupby('Department').apply(

    lambda x: x.nlargest(1,'Salary')
)

,,EmployeeID,Name,Gender,City,Salary,Bonus,Experience,Rating,Dept_avg,Rank
Department,,,,,,,,,,,
Finance,18,119,Divya,Female,Chennai,64000,5200,8,4.8,60250.000000,1.0
HR,15,116,Suresh,Male,Hyderabad,53000,3800,6,4.3,50333.333333,1.0
IT,5,106,Kiran,Male,Bangalore,82000,9000,7,4.9,73833.333333,1.0
Marketing,16,117,Kavya,Female,Bangalore,58000,4000,5,4.5,55000.000000,1.0
Sales,17,118,Varun,Male,Mumbai,51000,3100,4,4.1,48000.000000,1.0

# part 9 - value_counts()

In [55]:
#count departments

In [57]:
data['Department'].value_counts()

Department
IT           6
Finance      4
Sales        4
HR           3
Marketing    3
Name: count, dtype: int64

In [58]:
#count cities

data['City'].value_counts()

City
Hyderabad    5
Delhi        5
Mumbai       4
Chennai      3
Bangalore    3
Name: count, dtype: int64

In [59]:
# count the gender

data['Gender'].value_counts()

Gender
Male      11
Female     9
Name: count, dtype: int64

In [60]:
# count the rank

data['Rank'].value_counts()

Rank
3.0    5
1.0    5
2.0    5
4.0    3
6.0    1
5.0    1
Name: count, dtype: int64