# DATA MANIPULATION

## GOAL

In [1]:
🎯 Goal

By the end of Day 5, you will be able to:

Add new columns
Delete columns
Update existing values
Perform arithmetic operations
Use apply()
Use map()
Write lambda functions
Work with string data using .str
Handle basic date and time operations

<class 'SyntaxError'>: invalid character '🎯' (U+1F3AF) (3729724509.py, line 1)

In [2]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.421 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [3]:
import pandas as pd

print(pd.__version__)

3.0.5

## Loading the Dataset

In [4]:
import pandas as pd

data  = pd.read_csv("day-5.csv")

data

       Name  Age Department  Salary Joining_Date              Email Gender
0     Alice   24         IT   45000   2021-01-15    alice@gmail.com      F
1       Bob   29         HR   52000   2020-05-12      bob@gmail.com      M
2   Charlie   31      Sales   60000   2019-07-21  charlie@gmail.com      M
3     David   27    Finance   48000   2022-03-18    david@gmail.com      M
4       Eva   26  Marketing   55000   2021-11-10      eva@gmail.com      F
..      ...  ...        ...     ...          ...                ...    ...
95    Priya   25         IT   48000   2023-11-21   priya5@gmail.com      F
96    Rahul   44         HR   98000   2013-02-06   rahul5@gmail.com      M
97    Sneha   36      Sales   74000   2016-10-10   sneha5@gmail.com      F
98    Tarun   32    Finance   66000   2019-06-13   tarun5@gmail.com      M
99    Vijay   40  Marketing   85000   2014-01-31   vijay5@gmail.com      M

[100 rows x 7 columns]

## columsn

In [5]:
data.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Joining_Date', 'Email',
       'Gender'],
      dtype='str')

## 1 . Adding columns

In [6]:
# creating a new column called bonus 

data['Bonus'] = data['Salary']*0.10

data['Bonus']

0     4500.0
1     5200.0
2     6000.0
3     4800.0
4     5500.0
       ...
95    4800.0
96    9800.0
97    7400.0
98    6600.0
99    8500.0
Name: Bonus, Length: 100, dtype: float64

In [7]:
 # we can assign a constant values aslos

data['Country'] = 'India'

In [8]:
data['Country']

0     India
1     India
2     India
3     India
4     India
      ...
95    India
96    India
97    India
98    India
99    India
Name: Country, Length: 100, dtype: str

## 2 . Delete the columns from the dataset

In [12]:
# Deleting a single column

In [13]:
# Before deletion 


data

,Name,Age,Department,Salary,Joining_Date,Email,Gender,Bonus,Country
0,Alice,24,IT,45000,2021-01-15,alice@gmail.com,F,4500.0,India
1,Bob,29,HR,52000,2020-05-12,bob@gmail.com,M,5200.0,India
2,Charlie,31,Sales,60000,2019-07-21,charlie@gmail.com,M,6000.0,India
3,David,27,Finance,48000,2022-03-18,david@gmail.com,M,4800.0,India
4,Eva,26,Marketing,55000,2021-11-10,eva@gmail.com,F,5500.0,India
...,...,...,...,...,...,...,...,...,...
95,Priya,25,IT,48000,2023-11-21,priya5@gmail.com,F,4800.0,India
96,Rahul,44,HR,98000,2013-02-06,rahul5@gmail.com,M,9800.0,India
97,Sneha,36,Sales,74000,2016-10-10,sneha5@gmail.com,F,7400.0,India
98,Tarun,32,Finance,66000,2019-06-13,tarun5@gmail.com,M,6600.0,India
99,Vijay,40,Marketing,85000,2014-01-31,vijay5@gmail.com,M,8500.0,India

In [11]:
# after deletion , 


data.drop(columns = ['Country'])

,Name,Age,Department,Salary,Joining_Date,Email,Gender,Bonus
0,Alice,24,IT,45000,2021-01-15,alice@gmail.com,F,4500.0
1,Bob,29,HR,52000,2020-05-12,bob@gmail.com,M,5200.0
2,Charlie,31,Sales,60000,2019-07-21,charlie@gmail.com,M,6000.0
3,David,27,Finance,48000,2022-03-18,david@gmail.com,M,4800.0
4,Eva,26,Marketing,55000,2021-11-10,eva@gmail.com,F,5500.0
...,...,...,...,...,...,...,...,...
95,Priya,25,IT,48000,2023-11-21,priya5@gmail.com,F,4800.0
96,Rahul,44,HR,98000,2013-02-06,rahul5@gmail.com,M,9800.0
97,Sneha,36,Sales,74000,2016-10-10,sneha5@gmail.com,F,7400.0
98,Tarun,32,Finance,66000,2019-06-13,tarun5@gmail.com,M,6600.0
99,Vijay,40,Marketing,85000,2014-01-31,vijay5@gmail.com,M,8500.0

In [ ]:
Note : - It is a temporty dataFrame , if you want to make it permanent use inplace = True ,

eg : - data.drop(columns = ['Bonus'] , inplace  = True)

## Deleting multiple coulumns

In [15]:
# Deleting multiple columns 

data.drop(columns = ["Bonus","Country"])

       Name  Age Department  Salary Joining_Date              Email Gender
0     Alice   24         IT   45000   2021-01-15    alice@gmail.com      F
1       Bob   29         HR   52000   2020-05-12      bob@gmail.com      M
2   Charlie   31      Sales   60000   2019-07-21  charlie@gmail.com      M
3     David   27    Finance   48000   2022-03-18    david@gmail.com      M
4       Eva   26  Marketing   55000   2021-11-10      eva@gmail.com      F
..      ...  ...        ...     ...          ...                ...    ...
95    Priya   25         IT   48000   2023-11-21   priya5@gmail.com      F
96    Rahul   44         HR   98000   2013-02-06   rahul5@gmail.com      M
97    Sneha   36      Sales   74000   2016-10-10   sneha5@gmail.com      F
98    Tarun   32    Finance   66000   2019-06-13   tarun5@gmail.com      M
99    Vijay   40  Marketing   85000   2014-01-31   vijay5@gmail.com      M

[100 rows x 7 columns]

In [16]:
data

,Name,Age,Department,Salary,Joining_Date,Email,Gender,Bonus,Country
0,Alice,24,IT,45000,2021-01-15,alice@gmail.com,F,4500.0,India
1,Bob,29,HR,52000,2020-05-12,bob@gmail.com,M,5200.0,India
2,Charlie,31,Sales,60000,2019-07-21,charlie@gmail.com,M,6000.0,India
3,David,27,Finance,48000,2022-03-18,david@gmail.com,M,4800.0,India
4,Eva,26,Marketing,55000,2021-11-10,eva@gmail.com,F,5500.0,India
...,...,...,...,...,...,...,...,...,...
95,Priya,25,IT,48000,2023-11-21,priya5@gmail.com,F,4800.0,India
96,Rahul,44,HR,98000,2013-02-06,rahul5@gmail.com,M,9800.0,India
97,Sneha,36,Sales,74000,2016-10-10,sneha5@gmail.com,F,7400.0,India
98,Tarun,32,Finance,66000,2019-06-13,tarun5@gmail.com,M,6600.0,India
99,Vijay,40,Marketing,85000,2014-01-31,vijay5@gmail.com,M,8500.0,India

## 3 . Updating values in the dataset

## single value updation

In [18]:
data.loc[0,"Salary"] = 46000

In [19]:
data

,Name,Age,Department,Salary,Joining_Date,Email,Gender,Bonus,Country
0,Alice,24,IT,46000,2021-01-15,alice@gmail.com,F,4500.0,India
1,Bob,29,HR,52000,2020-05-12,bob@gmail.com,M,5200.0,India
2,Charlie,31,Sales,60000,2019-07-21,charlie@gmail.com,M,6000.0,India
3,David,27,Finance,48000,2022-03-18,david@gmail.com,M,4800.0,India
4,Eva,26,Marketing,55000,2021-11-10,eva@gmail.com,F,5500.0,India
...,...,...,...,...,...,...,...,...,...
95,Priya,25,IT,48000,2023-11-21,priya5@gmail.com,F,4800.0,India
96,Rahul,44,HR,98000,2013-02-06,rahul5@gmail.com,M,9800.0,India
97,Sneha,36,Sales,74000,2016-10-10,sneha5@gmail.com,F,7400.0,India
98,Tarun,32,Finance,66000,2019-06-13,tarun5@gmail.com,M,6600.0,India
99,Vijay,40,Marketing,85000,2014-01-31,vijay5@gmail.com,M,8500.0,India

## updating multiple values

In [44]:
data.loc[data['Department'].isin(['HR','IT']) , 'Salary'] +=1000

In [45]:
data[(data['Department'] == 'HR')| (data['Department'] == 'IT')]

,Name,Age,Department,Salary,Joining_Date,Email,Gender,Bonus,Country
0,Alice,24,IT,47000,2021-01-15,alice@gmail.com,F,4500.0,India
1,Bob,29,HR,54000,2020-05-12,bob@gmail.com,M,5200.0,India
5,Frank,35,IT,73000,2018-09-14,frank@gmail.com,M,7200.0,India
6,Grace,30,HR,53000,2020-02-20,grace@gmail.com,F,5100.0,India
10,Kiran,29,IT,66000,2020-04-08,kiran@gmail.com,M,6500.0,India
11,Lakshmi,34,HR,64000,2018-12-01,lakshmi@gmail.com,F,6200.0,India
15,Priya,24,IT,48000,2023-02-15,priya@gmail.com,F,4700.0,India
16,Rahul,36,HR,76000,2017-06-11,rahul@gmail.com,M,7400.0,India
20,Alice,23,IT,44000,2023-03-01,alice2@gmail.com,F,4300.0,India
21,Bob,30,HR,56000,2021-04-14,bob2@gmail.com,M,5400.0,India
25,Frank,38,IT,81000,2017-03-27,frank2@gmail.com,M,8000.0,India
26,Grace,29,HR,55000,2020-11-02,grace2@gmail.com,F,5300.0,India
30,Kiran,28,IT,63000,2021-08-17,kiran2@gmail.com,M,6200.0,India
31,Lakshmi,37,HR,72000,2017-09-13,lakshmi2@gmail.com,F,7000.0,India
35,Priya,22,IT,42000,2024-01-10,priya2@gmail.com,F,4100.0,India
36,Rahul,39,HR,84000,2016-05-18,rahul2@gmail.com,M,8200.0,India
40,Alice,25,IT,49000,2022-09-01,alice3@gmail.com,F,4800.0,India
41,Bob,31,HR,58000,2020-03-10,bob3@gmail.com,M,5600.0,India
45,Frank,40,IT,86000,2015-12-19,frank3@gmail.com,M,8500.0,India
46,Grace,27,HR,52000,2023-02-02,grace3@gmail.com,F,5000.0,India
50,Kiran,30,IT,69000,2019-11-20,kiran3@gmail.com,M,6800.0,India
51,Lakshmi,38,HR,78000,2016-08-24,lakshmi3@gmail.com,F,7600.0,India
55,Priya,23,IT,45000,2024-03-18,priya3@gmail.com,F,4400.0,India
56,Rahul,41,HR,92000,2015-01-11,rahul3@gmail.com,M,9000.0,India
60,Alice,26,IT,51000,2022-02-07,alice4@gmail.com,F,5000.0,India
61,Bob,32,HR,61000,2019-04-01,bob4@gmail.com,M,5900.0,India
65,Frank,42,IT,93000,2014-09-18,frank4@gmail.com,M,9200.0,India
66,Grace,28,HR,54000,2023-07-04,grace4@gmail.com,F,5200.0,India
70,Kiran,31,IT,71000,2019-02-12,kiran4@gmail.com,M,7000.0,India
71,Lakshmi,39,HR,83000,2015-10-21,lakshmi4@gmail.com,F,8100.0,India
75,Priya,24,IT,47000,2023-09-28,priya4@gmail.com,F,4600.0,India
76,Rahul,42,HR,96000,2014-04-05,rahul4@gmail.com,M,9400.0,India
80,Alice,27,IT,53000,2021-10-13,alice5@gmail.com,F,5200.0,India
81,Bob,33,HR,63000,2018-07-30,bob5@gmail.com,M,6100.0,India
85,Frank,43,IT,96000,2013-11-09,frank5@gmail.com,M,9500.0,India
86,Grace,29,HR,57000,2022-05-24,grace5@gmail.com,F,5500.0,India
90,Kiran,32,IT,74000,2018-11-05,kiran5@gmail.com,M,7300.0,India
91,Lakshmi,40,HR,86000,2014-12-14,lakshmi5@gmail.com,F,8400.0,India
95,Priya,25,IT,49000,2023-11-21,priya5@gmail.com,F,4800.0,India
96,Rahul,44,HR,100000,2013-02-06,rahul5@gmail.com,M,9800.0,India

## 4 . Arithmatic operations

In [47]:
# creating new columns 

data['Annual'] = data['Salary']*12

In [49]:
data

,Name,Age,Department,Salary,Joining_Date,Email,Gender,Bonus,Country,Annual
0,Alice,24,IT,47000,2021-01-15,alice@gmail.com,F,4500.0,India,564000
1,Bob,29,HR,54000,2020-05-12,bob@gmail.com,M,5200.0,India,648000
2,Charlie,31,Sales,60000,2019-07-21,charlie@gmail.com,M,6000.0,India,720000
3,David,27,Finance,48000,2022-03-18,david@gmail.com,M,4800.0,India,576000
4,Eva,26,Marketing,55000,2021-11-10,eva@gmail.com,F,5500.0,India,660000
...,...,...,...,...,...,...,...,...,...,...
95,Priya,25,IT,49000,2023-11-21,priya5@gmail.com,F,4800.0,India,588000
96,Rahul,44,HR,100000,2013-02-06,rahul5@gmail.com,M,9800.0,India,1200000
97,Sneha,36,Sales,74000,2016-10-10,sneha5@gmail.com,F,7400.0,India,888000
98,Tarun,32,Finance,66000,2019-06-13,tarun5@gmail.com,M,6600.0,India,792000
99,Vijay,40,Marketing,85000,2014-01-31,vijay5@gmail.com,M,8500.0,India,1020000

In [52]:
## calculating tax for each employee

data['Tax'] = data['Annual']*0.15

data['Tax']

0      84600.0
1      97200.0
2     108000.0
3      86400.0
4      99000.0
        ...
95     88200.0
96    180000.0
97    133200.0
98    118800.0
99    153000.0
Name: Tax, Length: 100, dtype: float64

In [54]:
# In hand salary 

data["In_hand"] = data['Annual'] - data['Tax']

data["In_hand"]

0      479400.0
1      550800.0
2      612000.0
3      489600.0
4      561000.0
        ...
95     499800.0
96    1020000.0
97     754800.0
98     673200.0
99     867000.0
Name: In_hand, Length: 100, dtype: float64

In [ ]:
Arithmetic operations

+
-
*
/
/
//
%
**

## 5 . apply()

In [ ]:
One of the most important Pandas functions.

It applies a function to each element or row.

In [55]:
# finding the len of the names

data['Name'].apply(len)

0     5
1     3
2     7
3     5
4     3
     ..
95    5
96    5
97    5
98    5
99    5
Name: Name, Length: 100, dtype: int64

In [57]:
# apply on functions

def major_or_not(age):
    if age>=18:
        return "Major"
    else:
        return "Minor"

data['Age_status'] = data['Age'].apply(major_or_not)    


data['Age_status']

0     Major
1     Major
2     Major
3     Major
4     Major
      ...
95    Major
96    Major
97    Major
98    Major
99    Major
Name: Age_status, Length: 100, dtype: str