## Understanding the csv file

In [3]:
# a csv means comma,separated values

## Loading the dataset

In [4]:
# importing the pandas library

import pandas as pd

data = pd.read_csv("student.csv")

data

,StudentID,Name,Age,Gender,Department,Year,CGPA,Attendance,City,Scholarship
0,1001,Alice,20,Female,AIML,2,9.2,92,Hyderabad,Yes
1,1002,Bob,21,Male,CSE,3,8.5,85,Vijayawada,No
2,1003,Charlie,20,Male,ECE,2,9.0,88,Visakhapatnam,Yes
3,1004,David,22,Male,AIML,4,8.8,81,Hyderabad,No
4,1005,Eva,21,Female,CSE,3,9.5,95,Tirupati,Yes
5,1006,Frank,20,Male,IT,2,8.7,86,Guntur,No
6,1007,Grace,22,Female,AIDS,4,9.1,90,Nellore,Yes
7,1008,Henry,21,Male,AIML,3,8.3,79,Kurnool,No
8,1009,Isha,20,Female,ECE,2,9.4,96,Hyderabad,Yes
9,1010,Jack,23,Male,CSE,4,8.1,75,Vijayawada,No
10,1011,Kavya,21,Female,IT,3,9.3,94,Tirupati,Yes
11,1012,Liam,22,Male,AIDS,4,8.6,84,Guntur,No
12,1013,Maya,20,Female,AIML,2,9.6,98,Hyderabad,Yes
13,1014,Noah,21,Male,CSE,3,8.4,82,Visakhapatnam,No
14,1015,Olivia,22,Female,ECE,4,9.0,91,Nellore,Yes

## 2 . head()

In [7]:
# it returns the top 5 rows 

data.head()

,StudentID,Name,Age,Gender,Department,Year,CGPA,Attendance,City,Scholarship
0,1001,Alice,20,Female,AIML,2,9.2,92,Hyderabad,Yes
1,1002,Bob,21,Male,CSE,3,8.5,85,Vijayawada,No
2,1003,Charlie,20,Male,ECE,2,9.0,88,Visakhapatnam,Yes
3,1004,David,22,Male,AIML,4,8.8,81,Hyderabad,No
4,1005,Eva,21,Female,CSE,3,9.5,95,Tirupati,Yes

In [8]:
#Example 2

data.head(10)

,StudentID,Name,Age,Gender,Department,Year,CGPA,Attendance,City,Scholarship
0,1001,Alice,20,Female,AIML,2,9.2,92,Hyderabad,Yes
1,1002,Bob,21,Male,CSE,3,8.5,85,Vijayawada,No
2,1003,Charlie,20,Male,ECE,2,9.0,88,Visakhapatnam,Yes
3,1004,David,22,Male,AIML,4,8.8,81,Hyderabad,No
4,1005,Eva,21,Female,CSE,3,9.5,95,Tirupati,Yes
5,1006,Frank,20,Male,IT,2,8.7,86,Guntur,No
6,1007,Grace,22,Female,AIDS,4,9.1,90,Nellore,Yes
7,1008,Henry,21,Male,AIML,3,8.3,79,Kurnool,No
8,1009,Isha,20,Female,ECE,2,9.4,96,Hyderabad,Yes
9,1010,Jack,23,Male,CSE,4,8.1,75,Vijayawada,No

## 3 . Tail()

In [9]:
# it returns the rows from the last 

# dafault 5 rows

data.tail()

,StudentID,Name,Age,Gender,Department,Year,CGPA,Attendance,City,Scholarship
10,1011,Kavya,21,Female,IT,3,9.3,94,Tirupati,Yes
11,1012,Liam,22,Male,AIDS,4,8.6,84,Guntur,No
12,1013,Maya,20,Female,AIML,2,9.6,98,Hyderabad,Yes
13,1014,Noah,21,Male,CSE,3,8.4,82,Visakhapatnam,No
14,1015,Olivia,22,Female,ECE,4,9.0,91,Nellore,Yes

In [10]:
# Example 2 

data.tail(7)

,StudentID,Name,Age,Gender,Department,Year,CGPA,Attendance,City,Scholarship
8,1009,Isha,20,Female,ECE,2,9.4,96,Hyderabad,Yes
9,1010,Jack,23,Male,CSE,4,8.1,75,Vijayawada,No
10,1011,Kavya,21,Female,IT,3,9.3,94,Tirupati,Yes
11,1012,Liam,22,Male,AIDS,4,8.6,84,Guntur,No
12,1013,Maya,20,Female,AIML,2,9.6,98,Hyderabad,Yes
13,1014,Noah,21,Male,CSE,3,8.4,82,Visakhapatnam,No
14,1015,Olivia,22,Female,ECE,4,9.0,91,Nellore,Yes

## 4 . shape

In [13]:
# returns the shape 

data.shape

# rows = 15

# cols  = 10

(15, 10)

In [14]:
# Accessing individuality

data.shape[0]

15

In [15]:
# only cols 

data.shape[1]

10

## 5 . columns

In [16]:
# returns the columns names

In [17]:
data.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'Department', 'Year', 'CGPA',
       'Attendance', 'City', 'Scholarship'],
      dtype='str')

In [18]:
# converting the names in to a list

list(data.columns)

['StudentID',
 'Name',
 'Age',
 'Gender',
 'Department',
 'Year',
 'CGPA',
 'Attendance',
 'City',
 'Scholarship']

## 6 . index

In [20]:
data.index

RangeIndex(start=0, stop=15, step=1)

##  7 . dtype

In [22]:
## it is used to represent the column type

data.dtypes

# int 64 - > the feature/column contains int data
# float64 -> the feature/column contains float data

#str -> the feature / column contains string values

StudentID        int64
Name               str
Age              int64
Gender             str
Department         str
Year             int64
CGPA           float64
Attendance       int64
City               str
Scholarship        str
dtype: object

## 7 . info()

In [23]:
# describes the info about the dataset

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    15 non-null     int64
 1   Name         15 non-null     str
 2   Age          15 non-null     int64
 3   Gender       15 non-null     str
 4   Department   15 non-null     str
 5   Year         15 non-null     int64
 6   CGPA         15 non-null     float64
 7   Attendance   15 non-null     int64
 8   City         15 non-null     str
 9   Scholarship  15 non-null     str
dtypes: float64(1), int64(4), str(5)
memory usage: 972.0 bytes

## 8 . describe

In [25]:
# stats info

data.describe()

         StudentID        Age       Year       CGPA  Attendance
count    15.000000  15.000000  15.000000  15.000000   15.000000
mean   1008.000000  21.066667   3.000000   8.900000   87.733333
std       4.472136   0.961150   0.845154   0.459814    6.766162
min    1001.000000  20.000000   2.000000   8.100000   75.000000
25%    1004.500000  20.000000   2.000000   8.550000   83.000000
50%    1008.000000  21.000000   3.000000   9.000000   88.000000
75%    1011.500000  22.000000   4.000000   9.250000   93.000000
max    1015.000000  23.000000   4.000000   9.600000   98.000000

In [ ]:
Coding Practice

Using the students.csv dataset:

Load the CSV into a DataFrame.
Display the first 4 rows.
Display the last 3 rows.
Print only the number of rows.
Print only the number of columns.
Print all column names.
Print the index.
Print the data type of each column.
Display the dataset information.
Display the statistical summary.
Find the average CGPA from the describe() output.
Find the highest and lowest age from the describe() output.
🎯 Day 2 Goal

By the end of today, you should be able to pick up any CSV file and answer these questions within 30 seconds:

How many rows and columns does it have?
What are the column names?
What data types are present?
Are there any missing values?
What do the first and last few rows look like?
What are the basic statistics of the numeric columns?