## DATA CLEANING AND MISSING VALUES

## GOAL

In [1]:
# Learn how to identify ,handle and clean  missing or incorrect data

## why is data cleaning is important ?

In [ ]:
Imagine you have customer data:

Name	Age	Salary
Alice	24	50000
Bob 	NaN	65000
Charlie	28	NaN
David	22	45000


Here NaN means null values / missing values

Questions:

How do you calculate the average age?
How do you train an ML model with missing values?

The answer is Data Cleaning.

## Topics

In [ ]:
1.Detecting Missing Values
2.isnull()
3.notnull()
4.dropna()
5.fillna()
6.Replacing values
7.Removing duplicate rows
8.Renaming columns
9.Changing data types
10.Practice Exercises

## 1 . Detecting Missing values

In [ ]:
Suppose your DataFrame looks like:

Name	Age	City
Alice	24	Hyderabad
Bob	    NaN	Chennai
Charlie	22	NaN

# Here NaN means (Not a Number) that means some value is missed in the row

In [3]:
# This function is used to check null values for each row

In [2]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.900 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

## Load the dataset

In [6]:
# import statement

import pandas as pd

data = pd.read_csv("Pandas_Day4_Practice_Dataset (1).csv")

data = pd.DataFrame(data)

data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## 2 . isnull()

In [7]:
# Checking for missing values

# True means missing values 

# False means value exist

data.isnull()

     Name    Age  Marks  Branch  Attendance   City
0   False  False  False   False       False  False
1   False  False   True   False       False  False
2   False  False  False   False        True  False
3   False  False  False   False       False  False
4   False   True  False   False       False  False
5   False  False  False   False       False  False
6   False  False  False   False       False   True
7   False  False   True   False       False  False
8   False  False  False   False       False  False
9   False  False  False   False       False  False
10  False  False  False   False       False  False
11  False  False  False   False        True  False
12  False  False  False   False       False  False
13  False   True  False   False       False  False
14  False  False   True   False       False  False
15  False  False  False   False       False   True

In [9]:
# Count the missing values

data.isnull().sum()

# This tells us exactly how many missing values exists in each column

Name          0
Age           2
Marks         3
Branch        0
Attendance    2
City          2
dtype: int64

## 3 . notnull()

In [10]:
# opposite to isnull()

# True = Value exist 

# False - missing value exist

In [11]:
data.notnull()

    Name    Age  Marks  Branch  Attendance   City
0   True   True   True    True        True   True
1   True   True  False    True        True   True
2   True   True   True    True       False   True
3   True   True   True    True        True   True
4   True  False   True    True        True   True
5   True   True   True    True        True   True
6   True   True   True    True        True  False
7   True   True  False    True        True   True
8   True   True   True    True        True   True
9   True   True   True    True        True   True
10  True   True   True    True        True   True
11  True   True   True    True       False   True
12  True   True   True    True        True   True
13  True  False   True    True        True   True
14  True   True  False    True        True   True
15  True   True   True    True        True  False

In [13]:
data.notnull().sum()

# Tells us exactly how many value exist for each column

Name          16
Age           14
Marks         13
Branch        16
Attendance    14
City          14
dtype: int64

## 4 . dropna()

In [ ]:
Removes the missing values from the dataset

Note :- if it finds any missing value in the row , it deletes the entire row 

Note :- use inplace = True , so the changes will effect the original dataset ,
other wise it updates the dataframe(data in our example) does not effect the original dataset

In [15]:
## removes the missing values 

data.dropna()

# i didn't use the inplace = True , because of my further examples

     Name   Age  Marks Branch  Attendance       City
0   Alice  20.0   85.0    CSE        92.0  Hyderabad
3   David  22.0   91.0    cse        95.0   Hydrabad
5   Frank  20.0   54.0    EEE        73.0  Bengaluru
8    Isha  19.0   95.0   AIML        98.0  Hyderabad
9    Jack  22.0   61.0   MECH        70.0       Pune
10  Kiran  21.0   78.0    CSE        85.0  Hyderabad
12  Mohan  19.0   74.0    ECE        79.0   Hydrabad

In [16]:
# it does not effect my original dataframe
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## Remove the column which contain the missing values

In [24]:
df = data
df.dropna(axis = 1)

df
# Two columns are removed

       Name Branch
0     Alice    CSE
1       Bob   AIML
2   Charlie    ECE
3     David    cse
4       Eva   AIML
5     Frank    EEE
6     Grace    CSE
7     Henry    ECE
8      Isha   AIML
9      Jack   MECH
10    Kiran    CSE
11    Latha   AIML
12    Mohan    ECE
13    Nisha    CSE
14      Bob   AIML
15    Grace    CSE

In [25]:
data

       Name Branch
0     Alice    CSE
1       Bob   AIML
2   Charlie    ECE
3     David    cse
4       Eva   AIML
5     Frank    EEE
6     Grace    CSE
7     Henry    ECE
8      Isha   AIML
9      Jack   MECH
10    Kiran    CSE
11    Latha   AIML
12    Mohan    ECE
13    Nisha    CSE
14      Bob   AIML
15    Grace    CSE

In [3]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.442 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [6]:
import pandas as pd

data = pd.read_csv("Pandas_Day4_Practice_Dataset (1).csv")

data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## Remove the row if any value contains missing value

In [7]:
data.dropna(how = 'any')

     Name   Age  Marks Branch  Attendance       City
0   Alice  20.0   85.0    CSE        92.0  Hyderabad
3   David  22.0   91.0    cse        95.0   Hydrabad
5   Frank  20.0   54.0    EEE        73.0  Bengaluru
8    Isha  19.0   95.0   AIML        98.0  Hyderabad
9    Jack  22.0   61.0   MECH        70.0       Pune
10  Kiran  21.0   78.0    CSE        85.0  Hyderabad
12  Mohan  19.0   74.0    ECE        79.0   Hydrabad

In [8]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## Remove the row if all values are null

In [9]:
# it removes the row if all values are null in the record other wise no deletion occured

data.dropna(how = 'all')

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

In [10]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## 5 . fillna()

In [11]:
# instedaing of deleting the rows , it fills the missing values

## filling with 0

In [12]:
data.fillna(0)

# see the missing value are filled with 0,doesnot modify the orifinal dataframe

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    0.0   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         0.0     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   0.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0          0
7     Henry  20.0    0.0    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         0.0     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   0.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    0.0   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0          0

In [13]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva   NaN   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha   NaN   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## -> Fill with mean

In [14]:
# I am filling the age columns

data['Age']=data['Age'].fillna(int(data['Age'].mean()))

In [15]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE         NaN     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva  20.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML         NaN     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha  20.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## Fill with median

In [16]:
# useful when our dataset contain outliers

In [17]:
data['Attendance'] = data['Attendance'].fillna(data['Attendance'].median())

In [18]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE        88.0     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva  20.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0        NaN
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML        88.0     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha  20.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0        NaN

## Forward fill

In [ ]:
copies the previous value

In [20]:
# in this example i am using the city column


data['City'] = data['City'].ffill()

In [21]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE        88.0     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva  20.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0  Bengaluru
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML        88.0     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha  20.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0    Chennai

## Back ward fill

In [22]:
data['City'] = data['City'].bfill()

data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE        88.0     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva  20.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0  Bengaluru
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML        88.0     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha  20.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0    Chennai

# 6 . Replace the value with other value

In [23]:
data['City'].replace('Hyderabad','Hyd')

0           Hyd
1       Chennai
2        Mumbai
3      Hydrabad
4           Hyd
5     Bengaluru
6     Bengaluru
7       Chennai
8           Hyd
9          Pune
10          Hyd
11       Mumbai
12     Hydrabad
13          Hyd
14      Chennai
15      Chennai
Name: City, dtype: str

In [24]:
data

       Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE        88.0     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva  20.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0  Bengaluru
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML        88.0     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha  20.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0    Chennai

## 7 . Detect the duplicated rows

In [26]:
# Find the duplicates

data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
dtype: bool

In [29]:
# count the duplicates 

data.duplicated().sum()


# In the data frame , we found that there is one duplicated row

np.int64(1)

# 8 . Remove the Duplicated rows

In [30]:
data.drop_duplicates

<bound method DataFrame.drop_duplicates of        Name   Age  Marks Branch  Attendance       City
0     Alice  20.0   85.0    CSE        92.0  Hyderabad
1       Bob  21.0    NaN   AIML        88.0    Chennai
2   Charlie  19.0   76.0    ECE        88.0     Mumbai
3     David  22.0   91.0    cse        95.0   Hydrabad
4       Eva  20.0   67.0   AIML        81.0  Hyderabad
5     Frank  20.0   54.0    EEE        73.0  Bengaluru
6     Grace  21.0   89.0    CSE        90.0  Bengaluru
7     Henry  20.0    NaN    ECE        84.0    Chennai
8      Isha  19.0   95.0   AIML        98.0  Hyderabad
9      Jack  22.0   61.0   MECH        70.0       Pune
10    Kiran  21.0   78.0    CSE        85.0  Hyderabad
11    Latha  20.0   82.0   AIML        88.0     Mumbai
12    Mohan  19.0   74.0    ECE        79.0   Hydrabad
13    Nisha  20.0   88.0    CSE        93.0  Hyderabad
14      Bob  21.0    NaN   AIML        88.0    Chennai
15    Grace  21.0   89.0    CSE        90.0    Chennai>

## 9 . save the processed data set

In [34]:
# to convert it in the csv file

data.to_csv("cleaned_dataset.csv",index =False)

In [ ]:
# convert into the excel file

data.to_excel("cleaned.xlsx",index = False)

## Interpolation

In [37]:
import pandas as pd
import numpy as np

data = {
    "Marks":[80,np.nan,np.nan,95]
}

df = pd.DataFrame(data)

df.interpolate()


# it fill the missing values based on the surrounded values

   Marks
0   80.0
1   85.0
2   90.0
3   95.0

In [ ]:
🎯 Day 4 Practice Checklist

Before moving to Day 5, make sure you can confidently answer yes to each of these:

☐ Create a DataFrame with missing values.
☐ Detect missing values using isnull() and isna().
☐ Count missing values in each column and in the whole DataFrame.
☐ Remove rows or columns with dropna().
☐ Use subset and thresh with dropna().
☐ Fill missing values with a constant, mean, median, and mode.
☐ Apply ffill() and bfill().
☐ Use interpolate() for numeric data.
☐ Replace values using replace().
☐ Detect and remove duplicate rows.
☐ Save the cleaned DataFrame to CSV and Excel.

If you master these topics, you'll have covered the core data-cleaning operations that are used in almost every real-world Pandas project.