# Combining DataFrames (Merge, Join, Concat)

In [ ]:
These operations are very important because in real-world projects, 
data is usually stored in multiple tables or CSV files.

In [1]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 2.386 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [2]:
import pandas as pd

df1 = pd.read_csv('std.csv')

df2 = pd.read_csv('marks.csv')

In [3]:
df1

   Student_ID     Name Department
0           1    Alice        CSE
1           2      Bob        ECE
2           3  Charlie         AI
3           4    David         IT

In [4]:
df2

   Student_ID  Marks
0           1     90
1           2     85
2           4     92
3           5     88

# part 1 concat()

In [5]:
# this function combines different datasets 

Used to combine DataFrames vertically (rows) or horizontally (columns).

In [8]:
df3 = pd.concat([df1,df2])

df3

   Student_ID     Name Department  Marks
0           1    Alice        CSE    NaN
1           2      Bob        ECE    NaN
2           3  Charlie         AI    NaN
3           4    David         IT    NaN
0           1      NaN        NaN   90.0
1           2      NaN        NaN   85.0
2           4      NaN        NaN   92.0
3           5      NaN        NaN   88.0

# part 2 merge()

In [ ]:
It is used to combine two DataFrames based on one or more common columns, just like SQL JOIN.


Parameters
Parameter	Description
left	    First DataFrame
right	    Second DataFrame
how	        Type of join
on	        Common column name
left_on	    Column name in left DataFrame
right_on	Column name in right DataFrame
suffixes	Rename duplicate column names

In [9]:
import pandas as pd

employees = pd.DataFrame({
    'EmpID':[101,102,103,104],
    'Name':['Alice','Bob','Charlie','David'],
    'DeptID':[1,2,2,3]
})

employees

   EmpID     Name  DeptID
0    101    Alice       1
1    102      Bob       2
2    103  Charlie       2
3    104    David       3

In [10]:
departments = pd.DataFrame({
    'DeptID':[1,2,4],
    'Department':['HR','IT','Sales']
})

departments

   DeptID Department
0       1         HR
1       2         IT
2       4      Sales

## 1 . inner join()

In [12]:
pd.merge(
    employees,
    departments,
    on = 'DeptID'
    
)

# by default inner join

# dept 3 and 4 is removed , because it is not present in both tables

   EmpID     Name  DeptID Department
0    101    Alice       1         HR
1    102      Bob       2         IT
2    103  Charlie       2         IT

## 2 . Left join()

In [14]:
pd.merge(
    employees,
    departments,
    on = 'DeptID',
    how = 'left'
)

# common from the both sides, retrive all values from the left

   EmpID     Name  DeptID Department
0    101    Alice       1         HR
1    102      Bob       2         IT
2    103  Charlie       2         IT
3    104    David       3        NaN

## 3 .Right join()

In [16]:
pd.merge(
    employees,
    departments,
    on = 'DeptID',
    how = 'right'
)

# common from the both dataframes , and all rows from the right dataframe(departments)

   EmpID     Name  DeptID Department
0  101.0    Alice       1         HR
1  102.0      Bob       2         IT
2  103.0  Charlie       2         IT
3    NaN      NaN       4      Sales

## 4 . outer()

In [17]:
#combine the both dataframes , which include all the rows from the both dataframes

pd.merge(
    employees,
    departments,
    on ='DeptID',
    how = 'outer'
)

   EmpID     Name  DeptID Department
0  101.0    Alice       1         HR
1  102.0      Bob       2         IT
2  103.0  Charlie       2         IT
3  104.0    David       3        NaN
4    NaN      NaN       4      Sales

## 5 . merge on different column names

In [ ]:
Sometimes the common columns have different names.

In [18]:
employees = pd.DataFrame({
    'EmployeeID':[101,102],
    'Dept':[1,2]
})

departments = pd.DataFrame({
    'DepartmentID':[1,2],
    'Department':['HR','IT']
})

In [19]:
print(employees)

print(departments)

   EmployeeID  Dept
0         101     1
1         102     2
   DepartmentID Department
0             1         HR
1             2         IT

In [21]:
pd.merge(
    employees,
    departments,
    left_on = 'Dept',
    right_on = 'DepartmentID'
)

   EmployeeID  Dept  DepartmentID Department
0         101     1             1         HR
1         102     2             2         IT

# Merge on Multiple Columns

In [23]:
df1 = pd.DataFrame({
    'ID':[1,1,2],
    'Year':[2024,2025,2025],
    'Marks':[80,85,90]
})

df2 = pd.DataFrame({
    'ID':[1,2],
    'Year':[2025,2025],
    'Grade':['A','A+']
})

In [24]:
print(df1)

print()

print(df2)

   ID  Year  Marks
0   1  2024     80
1   1  2025     85
2   2  2025     90

   ID  Year Grade
0   1  2025     A
1   2  2025    A+

In [25]:
pd.merge(
    df1,
    df2,
    on = ['ID','Year']
)

   ID  Year  Marks Grade
0   1  2025     85     A
1   2  2025     90    A+

## merge indicator

In [ ]:
Know where each row came from.

In [26]:
df1

   ID  Year  Marks
0   1  2024     80
1   1  2025     85
2   2  2025     90

In [27]:
df2

   ID  Year Grade
0   1  2025     A
1   2  2025    A+

In [29]:
pd.merge(
    df1,
    df2,
    on = 'ID',
    indicator = True
)

   ID  Year_x  Marks  Year_y Grade _merge
0   1    2024     80    2025     A   both
1   1    2025     85    2025     A   both
2   2    2025     90    2025    A+   both